### ISSUE TITLE
Robustness against adversarial attacks for ML security framework

### ISSUE THREAD

**Issue by saeid93** [adriangonz/sigstore-talk#1]
Hi @adriangonz ,
I was thinking maybe securing ML models could potentially go beyond tracking the file change and Pickle files and some ML-specific angles could be added to a Secure ML Platform. E.g. machine learning community has developed pretty sophisticated techniques for securing machine learning models against [adversarial attacks](https://adversarial-ml-tutorial.org/introduction/). Adding developed out-of-the-box support for evaluating models' robustness against such attacks could be some potential future direction for the development of MLServing platforms.

**Comment by adriangonz** [comment]
Hey @saeid93 ,

You're 100% correct.

There's this mantra in devsecops that any "security layer" can always be overcome by an attacker. So all you can do is put in enough layers so that an attacker essentially gives up. With that in mind, supply chain security is just a very thin layer covering one single angle and other measures - like protection against adversarial attacks - need to be considered. 

In this resource from [MITRE](https://atlas.mitre.org/),  they cover a good overview of different attacks that could get into a MLOps system. As you can see there, to actually be reasonably covered from every angle you will need to combine a different number of techniques.
